In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta

In [2]:
categories=pd.read_csv('datasets/domens_categories.csv')
ranks=pd.read_csv('datasets/ranked_top500000.csv')
secondary_prices=pd.read_csv('datasets/secondary_prices.csv')

Основной датасет

In [3]:
ton_domens=pd.read_csv('raw_datasets/ton_domains_history.csv').drop(['tx_hash','sale_type'],axis=1)

убираем .ton

In [4]:
ton_domens['domain_name']=ton_domens['domain_name'].map(lambda x: x.split('.')[0])

Так как это список продаж, один и тот же домен может встречаться несколько раз. Избавляемся от дубликатов, а актуальную цену берём по последней продаже

In [5]:
ton_domens['tx_time']=pd.to_datetime(ton_domens['tx_time'], unit='s')
ton_domens.sort_values(by='tx_time', inplace=True)
ton_domens=ton_domens.groupby(by='domain_name', as_index=False).agg(
    ton_price=('price_ton','last')
)
ton_domens=ton_domens.rename(columns={'domain_name': 'domain'})

# Собираем итоговый датасет

In [6]:
ton_dataset=ton_domens.merge(categories, on='domain', how='left')

In [7]:
len(ton_dataset[ton_dataset['category'].notna()])

3121

Всего 4894 совпадений по категориям

In [8]:
ton_dataset=ton_dataset.merge(ranks, on='domain', how='left')

In [9]:
ton_dataset[ton_dataset['rank200']==1]

,domain,ton_price,category,rank200,rank500,rank1000,rank10000,rank500000
9612,adobe,752.85,NaN,1.0,1.0,1.0,1.0,1.0
13156,amazon,500.00,NaN,1.0,1.0,1.0,1.0,1.0
13162,amazonalexa,1.00,NaN,1.0,1.0,1.0,1.0,1.0
13645,amplitude,10.00,NaN,1.0,1.0,1.0,1.0,1.0
13646,ampproject,49.96,NaN,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...
159987,xiaomi,419.96,NaN,1.0,1.0,1.0,1.0,1.0
164861,yahoo,740.00,NaN,1.0,1.0,1.0,1.0,1.0
164956,yandex,4200.00,Computers,1.0,1.0,1.0,1.0,1.0
165768,youtube,16000.00,Arts,1.0,1.0,1.0,1.0,1.0
166933,zoom,314.27,Business,1.0,1.0,1.0,1.0,1.0

In [12]:
secondary_prices

,domain_name,price,eth_reg_price,eth_sales_count,eth_sales_volume_usd,eth_last_sale_price_usd,usd_price,sol_sales_count,sol_sales_volume_usd,sol_last_sale_price_usd
0,rilxxlir,0.007863,17.22,NaN,NaN,NaN,19.387756,NaN,NaN,NaN
1,hansberry,0.003712,8.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,lalegend,0.002886,6.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,peterwagner,0.001976,4.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,stateland,0.000544,1.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
3490611,gangster-all-star,0.000481,1.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3490612,chain-feeds,0.002754,6.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3490613,68435,0.009944,21.78,1.0,38.41376,38.41376,NaN,NaN,NaN,NaN
3490614,prismai-deployer,0.001257,2.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3490615,💩🇷🇺,0.065988,144.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
ton_dataset

,domain,ton_price,category,rank200,rank500,rank1000,rank10000,rank500000
0,0---------------------------------------------...,1.04,NaN,NaN,NaN,NaN,NaN,NaN
1,0---------0,1.46,NaN,NaN,NaN,NaN,NaN,NaN
2,0---------1,1.00,NaN,NaN,NaN,NaN,NaN,NaN
3,0--------o0,1.00,NaN,NaN,NaN,NaN,NaN,NaN
4,0--0,100.00,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
167108,zzzzzzzzzzzzzzzzzz,1.00,NaN,NaN,NaN,NaN,NaN,NaN
167109,zzzzzzzzzzzzzzzzzzzzz,1.00,NaN,NaN,NaN,NaN,NaN,NaN
167110,zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz...,1.00,NaN,NaN,NaN,NaN,NaN,NaN
167111,zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz...,1.00,NaN,NaN,NaN,NaN,NaN,NaN
167112,zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz...,1.21,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
secondary_prices.rename(columns={'domain_name':'domain'},inplace=True)
ton_dataset=ton_dataset.merge(secondary_prices, on='domain', how='left')